# Generated by Django 3.0.6 on 2021-06-06 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('search_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='ecomweb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
