# Generated by Django 3.0.6 on 2021-06-06 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_data', '0002_auto_20210606_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
